# Generated by Django 3.0.8 on 2020-12-12 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('advertiser_management', '0011_auto_20201212_2151'),
        ('authtoken', '0003_tokenproxy'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertiser',
        ),
    ]
