# Generated by Django 3.0.8 on 2020-12-12 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0012_auto_20201212_2206'),
        ('user_management', '0003_advertiser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertiser',
            new_name='nAdvertiser',
        ),
    ]
