# Generated by Django 3.0.8 on 2020-12-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_auto_20201212_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nAdvertiser',
        ),
    ]
