# Generated by Django 3.0.8 on 2020-12-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'تبلیغات پایه'},
        ),
        migrations.AlterModelOptions(
            name='advertiser',
            options={'verbose_name': 'تبلیغات پایه'},
        ),
    ]
