# Generated by Django 3.0.8 on 2020-12-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0002_auto_20201201_0656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'تبلیغ', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AlterModelOptions(
            name='advertiser',
            options={'verbose_name': 'تبلیغ کننده', 'verbose_name_plural': 'تبلیغ کنندگان'},
        ),
        migrations.RenameField(
            model_name='ad',
            old_name='imgUrl',
            new_name='image',
        ),
    ]
