# Generated by Django 3.0.8 on 2020-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0003_auto_20201201_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='کلیک ها'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='views',
            field=models.IntegerField(default=0, verbose_name='مشاهده ها'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='کلیک ها'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='views',
            field=models.IntegerField(default=0, verbose_name='مشاهده ها'),
        ),
    ]
