# Generated by Django 3.0.8 on 2020-12-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0004_auto_20201201_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
    ]
