# Generated by Django 3.0.8 on 2020-12-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0006_auto_20201204_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='AdView',
        ),
    ]
