# Generated by Django 3.0.8 on 2020-12-08 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
        ('advertiser_management', '0007_auto_20201204_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='user_management.Advertiser', verbose_name='تبلیغ کننده'),
        ),
        migrations.DeleteModel(
            name='Advertiser',
        ),
    ]
