# Generated by Django 3.0.8 on 2020-12-12 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0008_auto_20201208_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addata',
            old_name='time',
            new_name='created_at',
        ),
    ]
