# Generated by Django 3.0.8 on 2020-12-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0009_auto_20201212_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان'),
        ),
    ]
