# Generated by Django 3.0.8 on 2020-12-12 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser', '0001_initial'),
        ('advertiser_management', '0010_auto_20201212_2119'),
    ]

    operations = [
    ]
