# Generated by Django 3.0.8 on 2020-12-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertiser_management', '0014_remove_ad_advertiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='nadvertiser',
            new_name='advertiser',
        ),
    ]
